
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package proyecto1compi1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR = 18;
  public static final int STR = 4;
  public static final int RES = 22;
  public static final int GRAPHPIE = 43;
  public static final int DOUBLE = 47;
  public static final int PC = 12;
  public static final int PA = 11;
  public static final int GRAPHBAR = 44;
  public static final int TITULOY = 42;
  public static final int TITULOX = 41;
  public static final int STAPR = 5;
  public static final int ENDPR = 6;
  public static final int EJEY = 36;
  public static final int EJEX = 35;
  public static final int COLUMN = 38;
  public static final int ARROBA = 14;
  public static final int TITULO = 40;
  public static final int DIV = 23;
  public static final int CC = 16;
  public static final int IG = 2;
  public static final int MIN = 30;
  public static final int CA = 15;
  public static final int ID = 48;
  public static final int MEDIANA = 27;
  public static final int EOF = 0;
  public static final int ASIG = 10;
  public static final int error = 1;
  public static final int COMA = 13;
  public static final int VALUES = 39;
  public static final int MODA = 28;
  public static final int MOD = 25;
  public static final int VARIANZA = 29;
  public static final int END = 9;
  public static final int MULTI = 24;
  public static final int SUM = 21;
  public static final int ARR = 20;
  public static final int UKN = 3;
  public static final int MEDIA = 26;
  public static final int POINTER = 17;
  public static final int EXEC = 34;
  public static final int LABEL = 37;
  public static final int MAX = 31;
  public static final int HISTOGRAM = 46;
  public static final int GRAPHLINE = 45;
  public static final int VAR = 19;
  public static final int DP = 7;
  public static final int PRINT = 33;
  public static final int CONSOLE = 32;
  public static final int PYC = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IG",
  "UKN",
  "STR",
  "STAPR",
  "ENDPR",
  "DP",
  "PYC",
  "END",
  "ASIG",
  "PA",
  "PC",
  "COMA",
  "ARROBA",
  "CA",
  "CC",
  "POINTER",
  "CHAR",
  "VAR",
  "ARR",
  "SUM",
  "RES",
  "DIV",
  "MULTI",
  "MOD",
  "MEDIA",
  "MEDIANA",
  "MODA",
  "VARIANZA",
  "MIN",
  "MAX",
  "CONSOLE",
  "PRINT",
  "EXEC",
  "EJEX",
  "EJEY",
  "LABEL",
  "COLUMN",
  "VALUES",
  "TITULO",
  "TITULOX",
  "TITULOY",
  "GRAPHPIE",
  "GRAPHBAR",
  "GRAPHLINE",
  "HISTOGRAM",
  "DOUBLE",
  "ID"
  };
}

